services:
  - type: web
    name: flipkart-gosats-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /
    autoDeploy: true